name: action workflow

on: [push]

jobs:
 run-github-actions:
   runs-on: ubuntu-latest
   steps:
     - name: List files
       run: |
        pwd
        ls
     - name: simple javascript actions
       uses: actions/hello-world-javascript-action@v1
       with:
        who-to-greet: DevOps hint 

   
