name: action workflow

on:
 schedule:
  -  cron: "* * * * *"
 pull_request:
  types: [closed,opened,assigned,reopened]

jobs:
 run-github-actions:
   runs-on: ubuntu-latest
   steps:
     - name: simple javascript actions
       uses: actions/hello-world-javascript-action@v1
       with:
        who-to-greet: DevOps hint 

   
