name: matrix

on: [push]

jobs:
  node_versions:
   strategy:
     matrix:
      node-versions: [6,7,8]
    runs-on: ubuntu-latest

    steps:
      - name: Check default Node.js version
        run: node -v

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-versions}}

      - name: After setup Node.js version
        run: node -v