name: run shell commands

on: [push]

jobs:
  run-shell:
    runs-on: ubuntu-latest
    steps:
     - name: run shell 
       run: echo " Hello AI World"
     - name: multi line script
       run: |
         node -v
         npm -v