name: shell commands

on: [push]

jobs:
  run-shell:
    runs-on: ubuntu-latest
    steps:
     - name: run shell 
       run: echo " Hello AI World"
     - name: multi line script
       run: |
         node -v
         npm -v
  run-windows-commands:
    runs-on: windows-latest
    steps:
     - name: powershell commands
       run: Get-Location
     - name: run Bash commands
       run: pwd
       shell: bash
